# logo图片名称，需要上传至img目录
logo: "logo-xchat.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "chat"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "仿真系统指令调度"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: "作战计划生成"
    prompt:
      '
      我们正在进行一场仿真演练，我方为红方，敌方为蓝方。
      下面是仿真系统提供的所有操作描述:
      1. 起飞
      字段名称	字段描述
      指令	操作类型，此处为“起飞”
      兵力名称	起飞的兵力名称
      速度	起飞速度（单位：公里/小时）
      航向	起飞航向（度）
      高度	起飞高度（米）
      载体名称	起飞地点（如航母或机场的名称）
      2. 机动控制
      字段名称	字段描述
      指令	操作类型，此处为“机动控制”
      兵力名称	被控制兵力的名称
      速度	机动速度（单位：公里/小时）
      航向	机动航向（度）
      高度	机动高度（米）
      3. 悬停
      字段名称	字段描述
      指令	操作类型，此处为“悬停”
      兵力名称	悬停的兵力名称
      4. 泛水
      字段名称	字段描述
      指令	操作类型，此处为“泛水”
      兵力名称	进行泛水的分队名称
      载体名称	进行泛水的舰艇名称
      5. 上船
      字段名称	字段描述
      指令	操作类型，此处为“上船”
      兵力名称	上船的分队名称
      载体名称	上船的舰艇名称
      6. 机降
      字段名称	字段描述
      指令	操作类型，此处为“机降”
      兵力名称	进行机降的分队名称
      载体名称	进行机降的飞机名称
      7. 登机
      字段名称	字段描述
      指令	操作类型，此处为“登机”
      兵力名称	登机的分队名称
      载体名称	登机的飞机名称
      8. 巡逻
      字段名称	字段描述
      指令	操作类型，此处为“巡逻”
      兵力名称	巡逻的兵力名称
      巡逻方式	“S型”
      9. 起航
      字段名称	字段描述
      指令	操作类型，此处为“起航”
      兵力名称	起航的潜艇名称
      速度	航行速度
      航向	航行航向
      深度	航行深度
      载体名称	起航点，如港口名称
      10. 返航
      字段名称	字段描述
      指令	操作类型，此处为“返航”
      兵力名称	返航的兵力名称
      基地名称	返航的机场或港口名称
      11. 传感器开机
      字段名称	字段描述
      指令	操作类型，此处为“传感器开机”
      兵力名称	操作的兵力名称
      传感器名称	需要开启的传感器名称
      工作模式	传感器的工作模式
      12. 传感器关机
      字段名称	字段描述
      指令	操作类型，此处为“传感器关机”
      兵力名称	操作的兵力名称
      传感器名称	需要关闭的传感器名称
      13. 所有传感器开机
      字段名称	字段描述
      指令	操作类型，此处为“所有传感器开机”
      兵力名称	操作的兵力名称
      14. 所有传感器关机
      字段名称	字段描述
      指令	操作类型，此处为“所有传感器关机”
      兵力名称	操作的兵力名称
      15. 攻击
      字段名称	字段描述
      指令	操作类型，此处为“攻击”
      兵力名称	发起攻击的兵力名称
      武器名称	使用的武器名称
      武器数量	使用的武器数量
      目标批号	攻击目标的批号
      16. 进入工事
      字段名称	字段描述
      指令	操作类型，此处为“进入工事”
      兵力名称	进入工事的兵力名称
      工事名称	目标工事名称
      17. 撤出工事
      字段名称	字段描述
      指令	操作类型，此处为“撤出工事”
      兵力名称	撤出的兵力名称
      工事名称	撤出的工事名称

      当前我方的兵力态势信息为：`
      辽宁号航母001（停有歼15机号001、歼15机号002、歼15机号003）
      驱逐舰158
      驱逐舰157
      反潜巡逻机131
      巡洋舰141
      潜艇101
      福田机场（停有歼15机号004、歼15机号005、歼15机号006、歼15机号007）
      歼15机号008`
      
      假设你是一名作战计划设计师，你的任务是分析指挥员指令并提取出核心流程，并且严格按照操作描述中的内容生成，不得超出范围。
      请仔细分析用户提供的文本，只输出核心的决策逻辑，不需要具体参数，其中所有武器装备和基地的名称必须与上述兵力态势信息对应。
      
      示例1
      指挥员指令：
      选取一架歼15战斗机，编号002，立即从辽宁号航母001起飞，进行高速前行，保障辽宁号的安全，并执行区域侦察任务。需要调整飞行参数以应对可能的恶劣天气。
      核心决策：
      1. 紧急起飞：命令歼15机号002从辽宁号航母001上紧急起飞。 
      2. 航线调整以避开恶劣天气：鉴于预测的恶劣天气，指令飞机调整航向，提升飞行高度，以确保安全。 
      3. 执行S型侦察巡逻：完成调整后，执行S型侦察巡逻，全面监视辽宁号周边的空域情况，确保无任何威胁接近。


      示例2
      指挥员指令：
      立即调动歼20战斗机，编号003，从福田机场起飞，速度全开，直奔目标海域。开启自动攻防系统，准备进行精确打击，任务完成后立即返回基地。
      核心决策：
      1. 高速起飞：指令歼20机号003从福田机场以最大速度起飞，调整航向与高度。 
      2. 开启自动攻防系统：激活全部自动攻防系统，准备进行目标打击。 

      示例3
      指挥员指令：
      即刻调动两架歼15战斗机，编号004和005，从辽宁号航母001起飞，执行紧急救援任务。飞行编队调整，同时执行全方位搜索。
      核心决策：
      1. 同时起飞：歼15机号004和005从辽宁号航母001同时起飞，确保协同操作。
      2. 飞行编队调整：调整编队飞行，机号004提升速度和高度，机号005相对减速和降低高度，确保全方位覆盖。
      3. 全方位搜索：执行S形搜索，同时监视大区域以定位紧急情况。
      
      如果指挥员的指令无法分析出核心的决策逻辑，请你设想出一个能达到指挥员目标的决策。
      现在请按照要求输出核心的决策逻辑
      指挥员指令：{question}
      核心决策：'

  PROMPT_TEMPLATE_2:
    title: "参数设定与解释"
    prompt:
      '
      我们正在进行一场仿真演练，我方为红方，敌方为蓝方。
      下面是仿真系统所有操作类型中的接口调度json字段描述:
      1. 起飞
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“起飞”	是
      兵力名称	String	起飞的兵力名称	是
      速度	Float	起飞速度（单位：公里/小时）	是
      航向	Float	起飞航向（度）	是
      高度	Float	起飞高度（米）	是
      载体名称	String	起飞地点（如航母或机场的名称）	是
      2. 机动控制
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“机动控制”	是
      兵力名称	String	被控制兵力的名称	是
      速度	Float	机动速度（单位：公里/小时）	否
      航向	Float	机动航向（度）	否
      高度	Float	机动高度（米）	否
      3. 悬停
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“悬停”	是
      兵力名称	String	悬停的兵力名称	是
      4. 泛水
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“泛水”	是
      兵力名称	String	进行泛水的分队名称	是
      载体名称	String	进行泛水的舰艇名称	是
      5. 上船
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“上船”	是
      兵力名称	String	上船的分队名称	是
      载体名称	String	上船的舰艇名称	是
      6. 机降
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“机降”	是
      兵力名称	String	进行机降的分队名称	是
      载体名称	String	进行机降的飞机名称	是
      7. 登机
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“登机”	是
      兵力名称	String	登机的分队名称	是
      载体名称	String	登机的飞机名称	是
      8. 巡逻
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“巡逻”	是
      兵力名称	String	巡逻的兵力名称	是
      巡逻方式	String	巡逻的方式（如“S型”）	是
      9. 起航
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“起航”	是
      兵力名称	String	起航的潜艇名称	是
      速度	Float	航行速度	是
      航向	Float	航行航向	是
      深度	Float	航行深度	是
      载体名称	String	起航点，如港口名称	是
      10. 返航
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“返航”	是
      兵力名称	String	返航的兵力名称	是
      基地名称	String	返航的机场或港口名称	是
      11. 传感器开机
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“传感器开机”	是
      兵力名称	String	操作的兵力名称	是
      传感器名称	String	需要开启的传感器名称	是
      工作模式	String	传感器的工作模式	是
      12. 传感器关机
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“传感器关机”	是
      兵力名称	String	操作的兵力名称	是
      传感器名称	String	需要关闭的传感器名称	是
      13. 所有传感器开机
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“所有传感器开机”	是
      兵力名称	String	操作的兵力名称	是
      14. 所有传感器关机
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“所有传感器关机”	是
      兵力名称	String	操作的兵力名称	是
      15. 攻击
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“攻击”	是
      兵力名称	String	发起攻击的兵力名称	是
      武器名称	String	使用的武器名称	是
      武器数量	Integer	使用的武器数量	是
      目标批号	Integer	攻击目标的批号	是
      16. 进入工事
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“进入工事”	是
      兵力名称	String	进入工事的兵力名称	是
      工事名称	String	目标工事名称	是
      17. 撤出工事
      字段名称	字段类型	字段描述	是否必须
      指令	String	操作类型，此处为“撤出工事”	是
      兵力名称	String	撤出的兵力名称	是
      工事名称	String	撤出的工事名称	是
      
      假设你是一名参数设计师，你的任务是分析指挥员决策，设计对应的参数数值，并且严格按照接口调度json字段描述中的内容生成，不得超出范围。
      请仔细分析用户提供的文本，输出核心的参数数值，其中所有参数名称必须与上述操作描述信息对应。
      
      示例1
      指挥员指令：
      选取一架歼15战斗机，编号002，立即从辽宁号航母001起飞，进行高速前行，保障辽宁号的安全，并执行区域侦察任务。需要调整飞行参数以应对可能的恶劣天气。
      
      核心决策：
      1. 紧急起飞：命令歼15机号002从辽宁号航母001上紧急起飞。 
      2. 航线调整以避开恶劣天气：鉴于预测的恶劣天气，指令飞机调整航向，提升飞行高度，以确保安全。 
      3. 执行S型侦察巡逻：完成调整后，执行S型侦察巡逻，全面监视辽宁号周边的空域情况，确保无任何威胁接近。
      
      参数设定与解释：
      ### （1）起飞
      + 指令："起飞",
      + 指令解释: "执行起飞指令",
      + 兵力名称: "歼15战斗机002"
      + 兵力名称解释: "决策选取歼15战斗机002战斗机",
      + 速度: 300.0,
      + 速度解释: "300公里/小时是假设歼15战斗机的最大允许起飞速度。在实际操作中，起飞速度会根据飞机的重量、气象条件以及跑道的长度等因素来确定。这里我们选择一个合理的速度来保证飞机能够安全起飞。"
      + 航向: 30.0,
      + 速度解释: "起飞航向通常会考虑航母的航向以及风向。航母的航向加上30度可以确保飞机在起飞后能够迅速转向到预定巡逻航线。",
      + 高度: 5000.0,
      + 高度解释: "选择5000米作为起飞高度是为了确保飞机能够避开恶劣天气，如雷暴或浓厚的云层。这个高度也足够飞机进行安全爬升到更高的巡航高度。",
      + 载体名称: "辽宁号航母001",
      + 载体名称解释: "这是起飞地点的标识，指明歼15战斗机是从辽宁号航母上起飞的。"
      ### （2）机动控制参数
      + 指令："机动控制",
      + 指令解释: "执行机动控制指令",
      + 兵力名称: "歼15战斗机002"
      + 兵力名称解释: "歼15战斗机002战斗机进行机动",
      + 速度: 600.0,
      + 速度解释: "600公里/小时这个速度是飞机在完成起飞后的巡航速度，600公里/小时是一个相对较高的速度，可以保证飞机快速到达巡逻区域并完成任务。"
      + 航向: 20.0,
      + 航向解释: "这个调整是为了避开预测的恶劣天气区域。通过改变航向，飞机可以绕过不利气象条件，确保飞行的安全。"
      + 高度: 8000.0,
      + 高度解释: "提升至8000米的高度可以确保飞机远离地面障碍物和大部分恶劣天气，同时这个高度对于大多数战斗机来说是经济的巡航高度。"
      ### （3）巡逻参数
      + 指令："巡逻",
      + 指令解释: "执行巡逻指令",
      + 兵力名称: "歼15战斗机002",
      + 兵力名称解释: "执行巡逻单位为歼15战斗机002",
      + 巡逻方式: "S型",
      + 巡逻方式解释": "S型巡逻是一种常见的巡逻模式，它允许飞机在巡逻区域内以曲线航线飞行，这样可以更好地覆盖监视区域，并提高发现潜在威胁的可能性。"
      
      示例2
      指挥员指令：
      即刻调动两架歼15战斗机，编号004和005，从辽宁号航母001起飞，执行紧急救援任务。飞行编队调整，同时执行全方位搜索。
      
      核心决策：
      1. 同时起飞：歼15机号004和005从辽宁号航母001同时起飞，确保协同操作。
      2. 飞行编队调整：调整编队飞行，机号004提升速度和高度，机号005相对减速和降低高度，确保全方位覆盖。
      3. 全方位搜索：执行S形搜索，同时监视大区域以定位紧急情况。
      
      参数设定与解释：
      ### （1）起飞
      + 指令: "起飞",
      + 指令解释: "执行起飞指令",
      + 兵力名称: "歼15战斗机004、歼15战斗机005",
      + 兵力名称解释: "决策选取歼15战斗机004和歼15战斗机005同时起飞，确保协同操作",
      + 速度: 300.0,
      + 速度解释: "300公里/小时是假设歼15战斗机的最大允许起飞速度。在实际操作中，起飞速度会根据飞机的重量、气象条件以及跑道的长度等因素来确定。这里我们选择一个合理的速度来保证飞机能够安全起飞。",
      + 航向: 30.0,
      + 航向解释: "起飞航向通常会考虑航母的航向以及风向。航母的航向加上30度可以确保飞机在起飞后能够迅速转向到预定搜索航线。",
      + 高度: 5000.0,
      + 高度解释: "选择5000米作为起飞高度是为了确保飞机能够避开恶劣天气，如雷暴或浓厚的云层。这个高度也足够飞机进行安全爬升到更高的巡航高度。",
      + 载体名称: "辽宁号航母001",
      + 载体名称解释: "这是起飞地点的标识，指明歼15战斗机是从辽宁号航母上起飞的。"
      ### （2）机动控制
      + 指令: "机动控制",
      + 指令解释: "执行机动控制指令",
      + 兵力名称: "歼15战斗机004",
      + 兵力名称解释: "决策选取歼15战斗机004执行高速前行，保障辽宁号的安全",
      + 速度: 600.0,
      + 速度解释: "600公里/小时这个速度是飞机在完成起飞后的巡航速度，600公里/小时是一个相对较高的速度，可以保证飞机快速到达巡逻区域并完成任务。",
      + 航向: 30.0,
      + 航向解释: "这个航向是为了避开预测的恶劣天气区域。通过改变航向，飞机可以绕过不利气象条件，确保飞行的安全。",
      + 高度: 8000.0,
      + 高度解释: "提升至8000米的高度可以确保飞机远离地面障碍物和大部分恶劣天气，同时这个高度对于大多数战斗机来说是经济的巡航高度。"
      ### （3）机动控制
      + 指令: "机动控制",
      + 指令解释: "执行机动控制指令",
      + 兵力名称: "歼15战斗机005",
      + 兵力名称解释: "决策选取歼15战斗机005相对减速和降低高度，确保全方位覆盖。",
      + 速度: 500.0,
      + 速度解释: "500公里/小时这个较低的速度是为了让005号机在较低的高度上能够更好地执行搜索任务，同时与004号机形成垂直梯队。",
      + 航向: 30.0,
      + 航向解释: "与004机保持相对位置，005号机的航向将会与004号机保持相对位置，以便两架飞机能够协同搜索，形成全方位覆盖。",
      + 高度: 6000.0,
      + 高度解释: "选择6000米的高度是为了让005号机能够在较低的高度上进行更细致的搜索，同时这个高度也足够安全，可以避免地面障碍物。"
      ### （4）巡逻
      + 指令: "巡逻",
      + 指令解释: "执行巡逻指令",
      + 兵力名称: "歼15战斗机004、歼15战斗机005",
      + 兵力名称解释: "执行巡逻单位为歼15战斗机004和歼15战斗机005，同时执行全方位搜索。",
      + 巡逻方式: "S型",
      + 巡逻方式解释: "S型巡逻是一种常见的巡逻模式，它允许飞机在巡逻区域内以曲线航线飞行，这样可以更好地覆盖监视区域，并提高发现潜在威胁的可能性。"

      
      如果指挥员的指令无法设定出核心的参数数值，请你设想出一个能达到指挥员目标的参数数值方案。
      现在请按照要求输出核心的参数设定与解释
      指挥员指令：{question}
      
      核心决策：{result1}
      
      参数设定与解释:'

  PROMPT_TEMPLATE_3:
    title: "调度指令生成"
    prompt: '
    我们正在进行一场仿真演练，我方为红方，敌方为蓝方。
    假设你是后端程序员，请你严格按照接口调度的json字段描述，根据识别的决策逻辑和参数设定，生成接口调度的 JSON 结构。
    该json结构应包含以下字段：
    {
      "指令序列": List[Dict["步骤":String, "调度数据": List[Dict]]
    }
    请根据实际情况进行填充。
    
    示例1
    指挥员指令：
    选取一架歼15战斗机，编号002，立即从辽宁号航母001起飞，进行高速前行，保障辽宁号的安全，并执行区域侦察任务。需要调整飞行参数以应对可能的恶劣天气。
    
    核心决策：
    1. 紧急起飞：命令歼15机号002从辽宁号航母001上紧急起飞。 
    2. 航线调整以避开恶劣天气：鉴于预测的恶劣天气，指令飞机调整航向，提升飞行高度，以确保安全。 
    3. 执行S型侦察巡逻：完成调整后，执行S型侦察巡逻，全面监视辽宁号周边的空域情况，确保无任何威胁接近。
    
    参数设定与解释：
    ### （1）起飞
    + 指令："起飞",
    + 指令解释: "执行起飞指令",
    + 兵力名称: "歼15战斗机002"
    + 兵力名称解释: "决策选取歼15战斗机002战斗机",
    + 速度: 300.0,
    + 速度解释: "300公里/小时是假设歼15战斗机的最大允许起飞速度。在实际操作中，起飞速度会根据飞机的重量、气象条件以及跑道的长度等因素来确定。这里我们选择一个合理的速度来保证飞机能够安全起飞。"
    + 航向: 30.0,
    + 速度解释: "起飞航向通常会考虑航母的航向以及风向。航母的航向加上30度可以确保飞机在起飞后能够迅速转向到预定巡逻航线。",
    + 高度: 5000.0,
    + 高度解释: "选择5000米作为起飞高度是为了确保飞机能够避开恶劣天气，如雷暴或浓厚的云层。这个高度也足够飞机进行安全爬升到更高的巡航高度。",
    + 载体名称: "辽宁号航母001",
    + 载体名称解释: "这是起飞地点的标识，指明歼15战斗机是从辽宁号航母上起飞的。"
    ### （2）机动控制参数
    + 指令："机动控制",
    + 指令解释: "执行机动控制指令",
    + 兵力名称: "歼15战斗机002"
    + 兵力名称解释: "歼15战斗机002战斗机进行机动",
    + 速度: 600.0,
    + 速度解释: "600公里/小时这个速度是飞机在完成起飞后的巡航速度，600公里/小时是一个相对较高的速度，可以保证飞机快速到达巡逻区域并完成任务。"
    + 航向: 20.0,
    + 航向解释: "这个调整是为了避开预测的恶劣天气区域。通过改变航向，飞机可以绕过不利气象条件，确保飞行的安全。"
    + 高度: 8000.0,
    + 高度解释: "提升至8000米的高度可以确保飞机远离地面障碍物和大部分恶劣天气，同时这个高度对于大多数战斗机来说是经济的巡航高度。"
    ### （3）巡逻参数
    + 指令："巡逻",
    + 指令解释: "执行巡逻指令",
    + 兵力名称: "歼15战斗机002",
    + 兵力名称解释: "执行巡逻单位为歼15战斗机002",
    + 巡逻方式: "S型",
    + 巡逻方式解释": "S型巡逻是一种常见的巡逻模式，它允许飞机在巡逻区域内以曲线航线飞行，这样可以更好地覆盖监视区域，并提高发现潜在威胁的可能性。"
    
    调度代码：
    ```json
    {
      "指令序列": [
        {
          "步骤": "紧急起飞",
          "调度数据":  [{
            "指令": "起飞",
            "兵力名称": "歼15机号002",
            "速度": 300.0,
            "航向": 30.0,
            "高度": 5000.0,
            "载体名称": "辽宁号航母001"
          }]
        },
        {
          "步骤": "航线调整以避开恶劣天气",
          "调度数据": [{
            "指令": "机动控制",
            "兵力名称": "歼15机号002",
            "速度": 600.0,
            "航向": 20.0,
            "高度": 8000.0
          }]
        },
        {
          "步骤": "执行S型侦察巡逻",
          "调度数据": [{
            "指令": "巡逻",
            "兵力名称": "歼15机号002",
            "巡逻方式": "S型"
          }]
        }
      ]
    }
    ```
    
    示例2
    指挥员指令：
    即刻调动两架歼15战斗机，编号004和005，从辽宁号航母001起飞，执行紧急救援任务。飞行编队调整，同时执行全方位搜索。
    
    核心决策：
    1. 同时起飞：歼15机号004和005从辽宁号航母001同时起飞，确保协同操作。
    2. 飞行编队调整：调整编队飞行，机号004提升速度和高度，机号005相对减速和降低高度，确保全方位覆盖。
    3. 全方位搜索：执行S形搜索，同时监视大区域以定位紧急情况。
    
    参数设定与解释：
    ### （1）起飞
    + 指令: "起飞",
    + 指令解释: "执行起飞指令",
    + 兵力名称: "歼15战斗机004、歼15战斗机005",
    + 兵力名称解释: "决策选取歼15战斗机004和歼15战斗机005同时起飞，确保协同操作",
    + 速度: 300.0,
    + 速度解释: "300公里/小时是假设歼15战斗机的最大允许起飞速度。在实际操作中，起飞速度会根据飞机的重量、气象条件以及跑道的长度等因素来确定。这里我们选择一个合理的速度来保证飞机能够安全起飞。",
    + 航向: 30.0,
    + 航向解释: "起飞航向通常会考虑航母的航向以及风向。航母的航向加上30度可以确保飞机在起飞后能够迅速转向到预定搜索航线。",
    + 高度: 5000.0,
    + 高度解释: "选择5000米作为起飞高度是为了确保飞机能够避开恶劣天气，如雷暴或浓厚的云层。这个高度也足够飞机进行安全爬升到更高的巡航高度。",
    + 载体名称: "辽宁号航母001",
    + 载体名称解释: "这是起飞地点的标识，指明歼15战斗机是从辽宁号航母上起飞的。"
    ### （2）机动控制
    + 指令: "机动控制",
    + 指令解释: "执行机动控制指令",
    + 兵力名称: "歼15战斗机004",
    + 兵力名称解释: "决策选取歼15战斗机004执行高速前行，保障辽宁号的安全",
    + 速度: 600.0,
    + 速度解释: "600公里/小时这个速度是飞机在完成起飞后的巡航速度，600公里/小时是一个相对较高的速度，可以保证飞机快速到达巡逻区域并完成任务。",
    + 航向: 30.0,
    + 航向解释: "这个航向是为了避开预测的恶劣天气区域。通过改变航向，飞机可以绕过不利气象条件，确保飞行的安全。",
    + 高度: 8000.0,
    + 高度解释: "提升至8000米的高度可以确保飞机远离地面障碍物和大部分恶劣天气，同时这个高度对于大多数战斗机来说是经济的巡航高度。"
    ### （3）机动控制
    + 指令: "机动控制",
    + 指令解释: "执行机动控制指令",
    + 兵力名称: "歼15战斗机005",
    + 兵力名称解释: "决策选取歼15战斗机005相对减速和降低高度，确保全方位覆盖。",
    + 速度: 500.0,
    + 速度解释: "500公里/小时这个较低的速度是为了让005号机在较低的高度上能够更好地执行搜索任务，同时与004号机形成垂直梯队。",
    + 航向: 30.0,
    + 航向解释: "与004机保持相对位置，005号机的航向将会与004号机保持相对位置，以便两架飞机能够协同搜索，形成全方位覆盖。",
    + 高度: 6000.0,
    + 高度解释: "选择6000米的高度是为了让005号机能够在较低的高度上进行更细致的搜索，同时这个高度也足够安全，可以避免地面障碍物。"
    ### （4）巡逻
    + 指令: "巡逻",
    + 指令解释: "执行巡逻指令",
    + 兵力名称: "歼15战斗机004、歼15战斗机005",
    + 兵力名称解释: "执行巡逻单位为歼15战斗机004和歼15战斗机005，同时执行全方位搜索。",
    + 巡逻方式: "S型",
    + 巡逻方式解释: "S型巡逻是一种常见的巡逻模式，它允许飞机在巡逻区域内以曲线航线飞行，这样可以更好地覆盖监视区域，并提高发现潜在威胁的可能性。"
    
    调度代码：
    ```json
    {
      "指令序列": [
        {
          "步骤": "同时起飞",
          "调度数据": [
            {
              "指令": "起飞",
              "兵力名称": "歼15战斗机004",
              "速度": 300.0,
              "航向": 30.0,
              "高度": 5000.0,
              "载体名称": "辽宁号航母001"
            },
            {
              "指令": "起飞",
              "兵力名称": "歼15战斗机005",
              "速度": 300.0,
              "航向": 30.0,
              "高度": 5000.0,
              "载体名称": "辽宁号航母001"
            }
          ]
        },
        {
          "步骤": "飞行编队调整",
          "调度数据": [
            {
              "指令": "机动控制",
              "兵力名称": "歼15战斗机004",
              "速度": 600.0,
              "航向": 30.0,
              "高度": 8000.0
            },
            {
              "指令": "机动控制",
              "兵力名称": "歼15战斗机005",
              "速度": 500.0,
              "航向": 30.0,
              "高度": 6000.0
            }
          ]
        },
        {
          "步骤": "执行全方位搜索",
          "调度数据": [
            {
              "指令": "巡逻",
              "兵力名称": "歼15战斗机004",
              "巡逻方式": "S型"
            },
            {
              "指令": "巡逻",
              "兵力名称": "歼15战斗机005",
              "巡逻方式": "S型"
            }
          ]
        }
      ]
    }
    ```
    
    如果下列提供的文本无法生成接口调度的 JSON 结构，请对指挥员进行提问以获取更详尽的信息。
    现在请按照要求输出生成接口调度的 JSON 结构
    指挥员指令：{question}
    
    核心决策：{result1}
    
    参数设定与解释：{result2}
    
    调度代码：'