# logo图片名称，需要上传至img目录
logo: "logo-xchat.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "chat"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "qwen"

# 界面标题
header: "双向认知功能演示"

# title为每个markdown框标题
# type分为stream和normal，即流式回答与非流式回答
# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompt_config:
  PROMPT_TEMPLATE_1:
    title: "场景理解"
    type: "stream"
    prompt:
      '
      你是一个军事仿真推演系统算子设计开发的专家，你对军事算子的业务执行流程和代码编写规范非常熟悉，现在我给你提供一段节选自其他军事仿真推演系统的代码片段，需要你结合通识和军事专业知识对这段代码进行阅读理解，分析这段代码中的哪些内容描述了哪个或哪些军事算子？逐个分析这些算子适用于哪个或哪些军事业务场景？最终用中文将结果总结输出即可，要求输出内容不超过50字，不要复述问题，不要有任何多余内容的回复。
      输出格式如下:
      
      ## 描述：

      （代码功能概括）
      
      ## 总结：
      
      （算子名称与适用场景）
      
      以下是给你提供的代码片段:{question}
      '

  PROMPT_TEMPLATE_2:
    title: "注释生成"
    type: "stream"
    prompt:
      '
      你是一个军事仿真推演系统算子设计开发的专家，你对军事算子的业务执行流程和代码编写规范非常熟悉。
      现在我给你提供一段节选自其他军事仿真推演系统的代码片段和其对应适用的业务场景，需要你在原代码基础上，对其中涉及业务流程和判断逻辑的内容进行注释。
      注释的格式为“简要的综述，加较为详细的解释描述”。
      请你直接输出完整的带有注释的代码，不要复述问题，不要在开头和结尾加上冗余回复，
      不要在结尾有任何多余内容的回复！！直接输出代码+注释即可。
      场景：{result1}
      代码：{question}
      '

  PROMPT_TEMPLATE_3:
    title: "流程json转写"
    type: "stream"
    prompt: '
    假设你是精通军事业务的程序员，请你根据用户提供的代码，生成决策树的 JSON 结构。
    每个节点对象应包括 id字段, 节点类型字段, 节点描述字段、以及下一节点数组，
    下面是示例结构：
    [
        {
            "id": 1,
            "节点类型": 执行节点,
            "节点描述": "示例",
            "下一节点": [2]
        },
        {
            "id": 2,
            "节点类型": 决策节点,
            "节点描述": "决策节点示例",
            "下一节点": [{
              "id": 3,
              "条件": "是"
            },
            {
              "id": 4,
              "条件": "否"
            }
            ]
        },
        {
            "id": 3,
            "节点类型": 执行节点,
            "节点描述": "示例",
            "下一节点": null
        },
        {
            "id": 4,
            "节点类型": 执行节点,
            "节点描述": "示例",
            "下一节点": null
        },
    ]
    id是当前节点的唯一标识；
    节点类型是当前节点的类型，包含两种类型：决策节点，执行节点；
    节点描述是当前节点的文字描述；
    下一节点是指向下一节点的ID列表，对于行动节点，下一节点映射出后续节点的id；对于决策节点，下一节点映射出基于不同条件的不同路径。
    请你确保 JSON 结构清晰、逻辑性强，并且不要在开头和结尾加上冗余回复，直接输出json即可。
    以下是给你提供的代码片段：{result2}
    json输出：
    '


show_graph:
  prompt: '
  下面是输入的示例结构：
  [
      {
          "id": 1,
          "节点类型": 执行节点,
          "节点描述": "执行示例1",
          "下一节点": [2]
      },
      {
          "id": 2,
          "节点类型": 决策节点,
          "节点描述": "决策示例1",
          "下一节点": [{
            "id": 3,
            "条件": "是"
          },
          {
            "id": 4,
            "条件": "否"
          }
          ]
      },
      {
          "id": 3,
          "节点类型": 执行节点,
          "节点描述": "执行示例3",
          "下一节点": null
      },
      {
          "id": 4,
          "节点类型": 执行节点,
          "节点描述": "执行示例4",
          "下一节点": null
      },
  ]
  
  说明：id是当前节点的唯一标识；
  节点类型是当前节点的类型，包含两种类型：决策节点，执行节点；
  节点描述是当前节点的文字描述；
  下一节点是指向下一节点的ID列表，对于行动节点，下一节点映射出后续节点的id；对于决策节点，下一节点映射出基于不同条件的不同路径。
  
  输出：
  digraph flowchart {
      "执行示例1" [shape=box];
      "决策示例1？" [shape=diamond];
      "执行示例3" [shape=box];
      "执行示例4" [shape=box];
            
      "决策示例1" -> "执行示例3" [label="是"];
      "决策示例1" -> "执行示例4" [label="否"];
  }

  假设你是一名数据结构程序员，擅长从json中抽取流程并生成DOT语言，上面是抽取示例。
  注意事项：
  1.节点需要纯中文，不要用id的英语作为节点名称；
  2.action节点为动作节点，需要用长方形(box)，decision节点为决策节点，需要用菱形(diamond)，并且下一节点的边上需要带上condition条件；
  3.流程图中可能会出现环形结构（即多个节点next指向同一个节点id，通常情况下decision节点会被多个next指向），需要你进行判断并把重复的next合并成一个节点，请不要出现重复的节点；
  4.除了根节点root外，尽可能不要出现游离的节点（即没有任何节点的next指向它时），如果出现了游离节点，你可以自己判断并把他接在符合逻辑的节点后面；
  现在我给你提供一段已有的流程json数据，需要你根据流程json，对其中的业务流程和判断逻辑进行梳理，需要将这套流程以如下DOT语言格式进行输出，请你不要复述问题，不能有任何多余内容的回复！
  
  流程json：
  {result3}
  输出：
  '