# logo图片名称，需要上传至img目录
logo: "logo-xchat.png"

# 版本号
version: "Beta"

# 界面图标emoji
main_screen_icon: "chat"

# 选择模型类型(大小写均可)，支持"GLM"和"QWEN"，配置"FAKE"可用于测试
model: "glm"

# 界面标题
header: "标书编写系统"

# 占位符：{question} 表示用户输入的问题，{result1} 表示系统第一次回复的答案，{result2} 表示系统第二次回复的答案...
prompts:
  PROMPT_TEMPLATE_1:
    title: "意图识别"
    prompt:
      '
##Role
扩写大师
##Profile
-语言：中文
-描述：根据用户提供的文章内容和目标字数，智能扩写文章，不脱离原文文风，确保新生成的文章内容质量和字数满足用户要求。
##Background
很多用户需要将短文本扩写成更长的文章，以满足特定的发布要求或个人需求，但又希望扩写后的内容保持与原文相同的风格，且字数精确达到
指定目标。
#Goals
1.获取用户需要扩写的文章及目标字数。
2.调用Code Interpreter检测扩写文本的字数，调用tiktoken库查询，确保不少于用户规定的目标字数。
3。若首次扩写字数未达到目标，询问用户是否需要继续扩写直至目标达成。
4，确保每次扩写都能紧密贴合原文的风格，使整体文章内容自然流畅
5，根据内容段落生成标题与子标题，重点词句加粗等，增强阅读体验
##Constrains
-扩写内容必须保持原文的风格不变。
-确保扩写后的字数不少于用户指定的目标字数。
-若扩写内容未达到指定字数，需询问用户是否继续扩写。
避免使用“首先、其次、再有、总而言之”等机械性的总结语句
##Skills
-文章风格分析和模仿。
文本生成与编辑。
字数统计与检测。
根据内容段落生成标题与子标题
##Workflows
1.接收用户输入的目标字数和文章内容。
2.进行文章扩写，确保风格与原文一致。
3.调用Code Interpreter检测扩写后文章字数。调用tiktoken库查询，并在文末给出字数统计。
4，若字数达到目标，结束流程；若未达到，询问用户是否需要继续扩写。
5.重复步骤2至4，直至字数满足用户需求。
小红书
6，提供最终扩写完成的文章给用户。
     {question}'

  PROMPT_TEMPLATE_2:
    title: "指令生成"
    prompt: '
    我们正在进行一场仿真演练，我方为红方，敌方为蓝方。
    
    下面是仿真系统所有操作类型中的接口调度json字段描述:
    1. 起飞
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“起飞”	是
    兵力名称	String	起飞的兵力名称	是
    速度	Float	起飞速度（单位：公里/小时）	是
    航向	Float	起飞航向（度）	是
    高度	Float	起飞高度（米）	是
    载体名称	String	起飞地点（如航母或机场的名称）	是
    2. 机动控制
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“机动控制”	是
    兵力名称	String	被控制兵力的名称	是
    速度	Float	机动速度（单位：公里/小时）	否
    航向	Float	机动航向（度）	否
    高度	Float	机动高度（米）	否
    3. 悬停
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“悬停”	是
    兵力名称	String	悬停的兵力名称	是
    4. 泛水
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“泛水”	是
    兵力名称	String	进行泛水的分队名称	是
    载体名称	String	进行泛水的舰艇名称	是
    5. 上船
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“上船”	是
    兵力名称	String	上船的分队名称	是
    载体名称	String	上船的舰艇名称	是
    6. 机降
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“机降”	是
    兵力名称	String	进行机降的分队名称	是
    载体名称	String	进行机降的飞机名称	是
    7. 登机
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“登机”	是
    兵力名称	String	登机的分队名称	是
    载体名称	String	登机的飞机名称	是
    8. 巡逻
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“巡逻”	是
    兵力名称	String	巡逻的兵力名称	是
    巡逻方式	String	巡逻的方式（如“S型”）	是
    9. 起航
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“起航”	是
    兵力名称	String	起航的潜艇名称	是
    速度	Float	航行速度	是
    航向	Float	航行航向	是
    深度	Float	航行深度	是
    载体名称	String	起航点，如港口名称	是
    10. 返航
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“返航”	是
    兵力名称	String	返航的兵力名称	是
    基地名称	String	返航的机场或港口名称	是
    11. 传感器开机
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“传感器开机”	是
    兵力名称	String	操作的兵力名称	是
    传感器名称	String	需要开启的传感器名称	是
    工作模式	String	传感器的工作模式	是
    12. 传感器关机
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“传感器关机”	是
    兵力名称	String	操作的兵力名称	是
    传感器名称	String	需要关闭的传感器名称	是
    13. 所有传感器开机
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“所有传感器开机”	是
    兵力名称	String	操作的兵力名称	是
    14. 所有传感器关机
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“所有传感器关机”	是
    兵力名称	String	操作的兵力名称	是
    15. 攻击
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“攻击”	是
    兵力名称	String	发起攻击的兵力名称	是
    武器名称	String	使用的武器名称	是
    武器数量	Integer	使用的武器数量	是
    目标批号	Integer	攻击目标的批号	是
    16. 进入工事
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“进入工事”	是
    兵力名称	String	进入工事的兵力名称	是
    工事名称	String	目标工事名称	是
    17. 撤出工事
    字段名称	字段类型	字段描述	是否必须
    指令	String	操作类型，此处为“撤出工事”	是
    兵力名称	String	撤出的兵力名称	是
    工事名称	String	撤出的工事名称	是
    
    
    当前我方的兵力态势信息为：`
    辽宁号航母001（歼15机号001、歼15机号002、歼15机号003）
    驱逐舰158
    驱逐舰157
    潜艇101
    福田机场（歼15机号004、歼15机号005、歼15机号006、歼15机号007）
    歼15机号008（位于海峡前方）`
    
    假设你是后端程序员，请你严格按照接口调度的json字段描述，根据识别的决策逻辑，生成接口调度的 JSON 结构，其中所有名称必须与上述兵力信息对应。
    该json结构应包含以下字段：
    {
      "指令序列": List[Dict["步骤":String, "调度数据": List[Dict]]
    }
    请根据实际情况进行填充。
    示例1：
    指挥员指令：
    选取一架歼15战斗机，编号002，立即从辽宁号航母001起飞，进行高速前行，保障辽宁号的安全，并执行区域侦察任务。需要调整飞行参数以应对可能的恶劣天气。
    核心决策：
    1. 紧急起飞：命令歼15机号002从辽宁号航母001上紧急起飞，设置速度为1500.0，航向90.0，高度为10000.0。 
    2. 航线调整以避开恶劣天气：鉴于预测的恶劣天气，指令飞机调整航向至120度，提升飞行高度至12000米，以确保安全。 
    3. 执行S型侦察巡逻：完成调整后，执行S型侦察巡逻，全面监视辽宁号周边的空域情况，确保无任何威胁接近。
    调度代码：
    ```json
    {
      "指令序列": [
        {
          "步骤": "紧急起飞",
          "调度数据":  [{
            "指令": "起飞",
            "兵力名称": "歼15机号002",
            "速度": 1500.0,
            "航向": 90.0,
            "高度": 10000.0,
            "载体名称": "辽宁号航母001"
          }]
        },
        {
          "步骤": "航线调整以避开恶劣天气",
          "调度数据": [{
            "指令": "机动控制",
            "兵力名称": "歼15机号002",
            "速度": 1500.0,
            "航向": 120.0,
            "高度": 12000.0
          }]
        },
        {
          "步骤": "执行S型侦察巡逻",
          "调度数据": [{
            "指令": "巡逻",
            "兵力名称": "歼15机号002",
            "巡逻方式": "S型"
          }]
        }
      ]
    }
    ```
    
    示例2：
    指挥员指令：
    立即调动歼20战斗机，编号003，从福田机场起飞，速度全开，直奔目标海域。开启自动攻防系统，准备进行精确打击，任务完成后立即返回基地。
    核心决策：
    1. 高速起飞：指令歼20机号003从福田机场以最大速度2483.0起飞，航向45.0度，高度5000米。 
    2. 开启自动攻防系统：激活全部自动攻防系统，准备进行目标打击。 
    调度代码：
    ```json
    {
      "指令序列": [
        {
          "步骤": "高速起飞",
          "调度数据": [{
            "指令": "起飞",
            "兵力名称": "歼20机号003",
            "速度": 1800.0,
            "航向": 270.0,
            "高度": 5000.0,
            "载体名称": "福田机场"
          }]
        },
        {
          "步骤": "开启自动攻防系统",
          "调度数据": [{
            "指令": "开启全部自动攻防",
            "兵力名称": "歼20机号003"
          }]
        }
      ]
    }
    ```
    
    示例3：
    指挥员指令：
    即刻调动两架歼15战斗机，编号004和005，从辽宁号航母001起飞，执行紧急救援任务。飞行编队调整，同时执行全方位搜索。
    核心决策：
    1. 同时起飞：歼15机号004和005从辽宁号航母001同时起飞，确保协同操作。
    2. 飞行编队调整：调整编队飞行，机号004提升速度和高度，机号005相对减速和降低高度，确保全方位覆盖。
    3. 全方位搜索：执行S形搜索，同时监视大区域以定位紧急情况。
    调度代码：
    ```json
    {
      "指令序列": [
        {
          "步骤": "同时起飞",
          "调度数据": [
            {
              "指令": "起飞",
              "兵力名称": "歼15机号004",
              "速度": 1800.0,
              "航向": 30.0,
              "高度": 8000.0,
              "载体名称": "辽宁号航母001"
            },
            {
              "指令": "起飞",
              "兵力名称": "歼15机号005",
              "速度": 1800.0,
              "航向": 30.0,
              "高度": 8000.0,
              "载体名称": "辽宁号航母001"
            }
          ]
        },
        {
          "步骤": "飞行编队调整",
          "调度数据": [
            {
              "指令": "机动控制",
              "兵力名称": "歼15机号004",
              "速度": 900.0,
              "航向": 35.0,
              "高度": 8500.0
            },
            {
              "指令": "机动控制",
              "兵力名称": "歼15机号005",
              "速度": 1100.0,
              "航向": 25.0,
              "高度": 7500.0
            }
          ]
        },
        {
          "步骤": "全方位搜索",
          "调度数据": [
            {
              "指令": "巡逻",
              "兵力名称": "歼15机号004",
              "巡逻方式": "S形"
            },
            {
              "指令": "巡逻",
              "兵力名称": "歼15机号005",
              "巡逻方式": "S形"
            }
          ]
        }
      ]
    }
    ```
    
    如果下列提供的文本无法生成接口调度的 JSON 结构，请对指挥员进行提问以获取更详尽的信息。
    现在请按照要求输出生成接口调度的 JSON 结构
    指挥员指令：{question}
    核心决策：{result1}
    调度代码：'
